### ISSUE TITLE
로그아웃 클릭 시, 로그인 화면으로 넘어가지 못하는 오류

### ISSUE THREAD

**Issue by minenam** [elice-ai4-project/portfolio-share-service#31]
### 오류 상황
- 포트폴리오에서 '로그아웃'을 눌렀을 때, 로그인 화면으로 넘어가지 못하고 빈 화면이 나타남
- 이때, 새로고침하면 다시 로그인 화면으로 이동함

### 문제 화면
![image](https://user-images.githubusercontent.com/35288895/170487747-1f31a8e3-31da-4f58-a3ef-19754fa69a9a.png)

```
CommentElement.js:49 
        
       Uncaught TypeError: Cannot read properties of null (reading 'id')
    at CommentElement (CommentElement.js:49:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at beginWork (react-dom.development.js:19063:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)

(후략)
```

**Comment by minenam** [comment]
https://github.com/elice-ai4-project/portfolio-share-service/commit/9126ba9e5e7e3c9e734181b1018edcba8765bf05 해결
